import type { Metadata } from 'next';
import { Inter, Assistant } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/lib/providers/themeProvider';
import { mergeClassNames } from '@/lib';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

const assistant = Assistant({
  subsets: ['latin'],
  variable: '--font-assistant',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mergeClassNames('bg-background', inter.className)}>
        <Header>
          Instant Insurance Claim Payout Service
          <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
            {children}
          </ThemeProvider>
        </Header>
      </body>
    </html>
  );
}
